const tools=[
{name:"HubSpot",url:"https://www.hubspot.com/",tags:["professional","general","crm","marketing","small","growing","large","simple","best","standard","premium","flexible"],fit:"Strong all-in-one option",why:["CRM can start simply and expand","Combines sales, marketing, and service tools"],caution:"Advanced hubs can become expensive and require deliberate setup."},
{name:"Jobber",url:"https://www.getjobber.com/",tags:["field","scheduling","invoicing","solo","small","growing","simple","standard","premium","flexible"],fit:"Built for home-service work",why:["Connects requests, quotes, jobs, and invoices","Useful dispatch and customer communication workflow"],caution:"Less suitable for businesses that do not manage field jobs."},
{name:"Housecall Pro",url:"https://www.housecallpro.com/",tags:["field","scheduling","invoicing","small","growing","simple","standard","premium","flexible"],fit:"Field-service alternative",why:["Scheduling and dispatch are central","Includes customer and payment workflows"],caution:"Compare plan limits carefully as the team grows."},
{name:"Gusto",url:"https://gusto.com/",tags:["field","professional","retail","general","payroll","small","growing","simple","standard","premium","flexible"],fit:"Approachable payroll option",why:["Payroll and tax workflows in one place","Supports hiring and benefits as needs expand"],caution:"Very small teams should compare total cost with simpler payroll options."},
{name:"Shopify",url:"https://www.shopify.com/",tags:["retail","commerce","solo","small","growing","large","simple","standard","premium","flexible"],fit:"Commerce-first platform",why:["Strong online-store ecosystem","Can support in-person and online selling"],caution:"Apps and payment costs can materially increase the total monthly expense."},
{name:"FreshBooks",url:"https://www.freshbooks.com/",tags:["professional","general","invoicing","solo","small","simple","lean","standard","flexible"],fit:"Simple billing workflow",why:["Designed around invoices and expenses","Accessible for service businesses and solo operators"],caution:"Growing companies may eventually need deeper accounting or operations tools."},
{name:"Semrush",url:"https://www.semrush.com/",tags:["professional","retail","general","marketing","small","growing","large","best","premium","flexible"],fit:"Research-heavy marketing toolkit",why:["Broad SEO and competitive-research capabilities","Useful when organic search is a serious growth channel"],caution:"It is difficult to justify if no one will consistently use the data."}
];
let step=1;const total=5;const form=document.querySelector("#stack-form");const next=document.querySelector("#next");const back=document.querySelector("#back");const error=document.querySelector("#form-error");
function showStep(){document.querySelectorAll(".question").forEach(q=>q.classList.toggle("active",Number(q.dataset.step)===step));document.querySelector("#step-count").textContent=`Question ${step} of ${total}`;document.querySelector("#progress-bar").style.width=`${step/total*100}%`;back.disabled=step===1;next.textContent=step===total?"Show my matches":"Continue";error.textContent="";}
function selected(name){return form.querySelector(`input[name="${name}"]:checked`)?.value}
function currentName(){return ["industry","team","priority","budget","approach"][step-1]}
next.addEventListener("click",()=>{if(!selected(currentName())){error.textContent="Choose an option to continue.";return}if(step<total){step++;showStep();return}renderResults()});
back.addEventListener("click",()=>{if(step>1){step--;showStep()}});
function renderResults(){const answers=["industry","team","priority","budget","approach"].map(selected);const scored=tools.map((tool,index)=>({tool,index,score:answers.reduce((n,a)=>n+(tool.tags.includes(a)?1:0),0)+(tool.tags.includes(selected("priority"))?3:0)+(tool.tags.includes(selected("industry"))?2:0)})).sort((a,b)=>b.score-a.score||a.index-b.index).slice(0,3);document.querySelector("#result-grid").innerHTML=scored.map(({tool},i)=>`<article class="result-card"><span class="result-rank">Match ${i+1}</span><h3>${tool.name}</h3><span class="fit">${tool.fit}</span><ul>${tool.why.map(w=>`<li>${w}</li>`).join("")}</ul><p class="caution"><b>Watch for:</b> ${tool.caution}</p><a class="vendor-link" href="${tool.url}" target="_blank" rel="nofollow noopener">Visit ${tool.name}</a></article>`).join("");document.querySelector("#results").hidden=false;document.querySelector("#results").scrollIntoView({behavior:"smooth"});}
document.querySelector("#restart").addEventListener("click",()=>{form.reset();step=1;showStep();document.querySelector("#results").hidden=true;document.querySelector("#matcher").scrollIntoView({behavior:"smooth"})});
document.querySelector("#year").textContent=new Date().getFullYear();showStep();